import "./globals.css";
import LayoutClient from "./(client)/layoutclient";
import Providers from "./provider.jsx";
import Navbar from "@/components/principal/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col w-[100%]">
        <Providers>
          <Navbar/>
     {children}
     </Providers>
      </body>
    </html>
  );
}
